version: '3.6'

services:
  mongodb:
    container_name: mongodb
    image: mongo
    volumes:
      - ~/mongo:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=socketio
    networks:
      - webapp-network
networks:
  webapp-network:
    driver: bridge